---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "bmspy.name" . }}
  namespace: {{ .Values.namespace | default "bms" }}
  labels:
    {{- include "bmspy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "bmspy.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bmspy.name" . }}
        {{- include "bmspy.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "bmspy.name" . }}
          image: {{ required "A valid `image` must be provided." .Values.image }}:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          env:
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bmspy
                  key: SLACK_APP_TOKEN
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bmspy
                  key: SLACK_BOT_TOKEN
          {{ if .Values.args -}}
          command: ["pipenv"]
          args:
            - run
            - ./bmspy.py
            {{- .Values.args | toYaml | nindent 12 }}
          {{- end }}
{{- if .Values.config | default false }}
          volumeMounts:
            - name: config
              mountPath: /home/bmspy/settings.yaml
              subPath: settings.yaml
      volumes:
        - name: config
          configMap:
            name: {{ include "bmspy.name" . }}
{{- end }}
      restartPolicy: Always
